# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -la
            echo "^^^ That should look familiar"
      - run:
          name: Running in a Unique Container
          command: |
            whoami
